[build]
  # Répertoire de publication (où se trouvent les fichiers à déployer)
  publish = "."
  
  # Commande de build (optionnelle pour un site statique)
  command = "echo 'Site statique - pas de build nécessaire'"

[build.environment]
  # Variables d'environnement si nécessaires
  NODE_VERSION = "18"

# Configuration des redirections et headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuration pour les fichiers statiques
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Gestion des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404